version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5450:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/peliculas_create.sql:/docker-entrypoint-initdb.d/peliculas_create.sql.sql
volumes:
  db:
    driver: local